### ISSUE TITLE
Why limiting the amount of boards to 8?

### ISSUE THREAD

**Issue by raffaelj** [greggigon/mpk-desktop-app#19]
Is there a reason to limit the amount of boards to 8? I found the [config file][1] to change it, but I don't see any reason for it (besides a possible paid pro version in the future).

[1]: https://github.com/greggigon/mpk-desktop-app/blob/develop/app/constants/appConfiguration.ts#L1

**Comment by greggigon** [comment]
Honest answer:

- In the true spirit of Kanban and Personal Kanban, having too many boards makes the work less visible. As you only have one life, all the items on the board cut through your life, and show work that has to be completed at some point. If you start separating the work too multiple boards, work becomes less visible, harder to prioritise. As our work, personal life, hobbies and everything is intertwined in our life, so we should represent it on a single board as clearly as possible. I think that 8 boards is more than enough for a personal Kanban, but I'm open to be convinced otherwise 😄 
- And second point is, I didn't want to deal with too many entries on the board switcher, at least not yet. 

I don't have a plan to make the application into paid version. I will like to keep the 8 boards limit for now and see if more people would ask about the similar feature in the future.

@raffaelj what you think?

**Comment by raffaelj** [comment]
> I don't have a plan to make the application into paid version.

Good to know - and it wouldn't be a problem, if you would do so. I saw a project recently, where the desktop app is for free and the mobile app is paid. It just becomes a problem, if the source code gets cluttered with useless limitations, analytics, third party requests and ads...

> And second point is, I didn't want to deal with too many entries on the board switcher, at least not yet.

Good point. It might get perfomance issues with too much items...

> having too many boards makes the work less visible.
> [...] but I'm open to be convinced otherwise

I get the point, but I always have multiple (side) projects and too many notes (analog and digital) and I tried to sort them multiple times over the past years - without success.

I use Github issues for multiple open source software projects to keep track of bugs and ideas.
I have `todo.md` files in multiple project folders for clients. Sometimes I loose track of an important one and sometimes a projects starts months after the first meeting. The result is a mix of notes and tasks, that don't belong in a folder structure with "current projects" and so on.
Sometimes I have project ideas, which start as a project_idea.md - and then I forget about them...

I'm not sure, if a kanban app can solve my personal management problems ;-) - but I got quite good results with [Kanboard][1] a few years ago. The main problem was, that it is a (self hosted) server solution, which requires running a server on localhost and logging in via browser or even having to care about server security... Things, I want to avoid for a task list.

So my thoughts are: Having not enough boards, makes the work *invisible*. Having too many boards, makes the work *less visible*. Maybe adding priorities to boards and having "Pinned boards" or/and "Recent boards" could solve the problem of having too many of them. Multiple portable instances or profiles per project/per client etc. would also be useful.

[1]: https://kanboard.org/

**Comment by greggigon** [comment]
Let's keep it 8 for now and see if it's not enough in the near future. Perhaps you could come up with an interesting UX/UI for the board switcher.

Also, I thought I share how I use My Personal Kanban, perhaps it would give you some inspiration 8-)

- I use 3 boards
- On board 1 I have my **current** work, that I know exactly what needs to be done to complete it. I use tags for categorization and I keep it simple, 3 columns for my workflow, TODO, IN PROGRESS, DONE. I also limit my WIP to 3 so I don't context switch too much. I actually mix Personal stuff with Work and I separate it with TAGS. If I'm blocked on something I use FLAG.
- Second board is a board of **ideas** and bigger initiative that I'm not 100% sure how to progress yet but I already committed myself to do it. 3 columns again, tags for categorization. I create detailed cards in the  **current** board, when I know how to progress with it. 
- Third board is the board of **Long Term** goals and Ideas. A dumping ground for thoughts that could perhaps develop over time and promote to the second board. This board I use to peak every now and again in order to remind myself why am I doing what I'm doing  and to see if ideas from some time ago make sense now to be worked on 😄

**Comment by raffaelj** [comment]
Thanks for sharing. Mixing personal and work sounds like a great idea to reduce complexity... I'll give it a try.

I would still recommend, not to hardcode the amount of 8, but to make it configurable.
