### ISSUE TITLE
used my personal kanban but lost day's worth of everything entered

### ISSUE THREAD

**Issue by k-byun** [greggigon/mpk-desktop-app#55]
Hi, 
I know that the predecessor - my personal kanban (MPK)- is no longer supported but I am just posting this issue here.

I loved MPK for a day and started putting in everything.  Then I noticed when I had opened two browsers entering to the same board, new cards created wouldn't be opened on another.  In my attempt to troubleshoot this, I went in to Chrome > Settings > _entered "cache" in the search_ > selected **Clear browsing data** > _chose last 24 hours in "Time range" dropdown_ and _selected all three boxes - "Browsing history", "Cookies and other site data", and Cached images and files_ > click **Clear data**.

Now, I've lost everything - all the boards and all the cards.  I'd love to recover them but can't find a way to recover them.  It would have been nice to mention this sort of **critical** issue at the project page so that people wouldn't accidentally go through what I had gone through.

I would love to retry the my personal kanban tool but it seems too risky to use the tool and without this fix, the tool itself seems very risky tool to use and be recommended (I was recommended of this tool by someone I follow as well).

Thanks

**Comment by Da-kota** [comment]
From [https://greggigon.github.io/my-personal-kanban/](https://greggigon.github.io/my-personal-kanban/):

"...
[The] Application persists Kanban boards in local browser storage. Unfortunately storage is not shared between different browsers. That's why same page opened in different browsers will not have the same Kanban content.

If you need you can export content of one or all Kanbans into a JSON file.
..."

Good luck with 'rebuilding'.
